### ISSUE TITLE
supporting eyeglass modules that already have their own main.

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#10]
A lot of existing sass packages are already npm modules for one reason or another and they might have their own main script that does something completely different from the standard.

Specifically, I'm trying to support making [true](https://github.com/ericam/true/blob/master/package.json) an eyeglass module.

A few options I see:

1. Try to `require("my_npm_module/eyeglass-exports")` and fall back to `require("my_npm_module")` if that doesn't work.
2. Always `require("my_npm_module")` but first check for `require("my_npm_module").eyeglass` so that if the can return an eyeglass function attached to some other object.
3. Don't support this... they would need to make a new npm module that wraps their other one and conforms to our existing api.

**Comment by Jakobo** [comment]
I think I might prefer an `eyeglass / eyeglass-exports` property in `package.json` which we will resolve and read in. Using our resolve function does properly resolve `my_npm_module/package.json`. This can override a `main` property for npm modules that intend `main` to be something else but still want to integrate with eyeglass.

This pattern has been used in other libraries that want to know more about npm modules without necessarily forcing `main` adoption or alterations.

**Comment by chriseppstein** [comment]
Fixed by 7f978dfb1945d78726ee0ea425b199c128c20df3
