### ISSUE TITLE
Cross-compaitbility using a compatibility file

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#100]
As an index.scss is used as main @import point, 
ruby sass and plain node-sass would need different @import styles 
@import 'index'; instead @import 'module-name';

One simple/elegant way to fix this would be adding a compatibility file 
with the same name as the eyeglass module and let it @import 'index';
Then all sass variants can @import the module with same name and styles.

So one could add this as proposal to the documentation how an eyeglass module is prepared.

Thank you and
With best regards

**Comment by chriseppstein** [comment]
I think eyeglass should be able to interop with any project that is following the Sass loadpath conventions without that project needing any eyeglass specific sass files.

**Comment by chriseppstein** [comment]
Just wrote a test and realized that this already works. Just name your file the same name as your eyeglass module's name in your module's sass directory and it will be imported by default when importing your module. You don't have to name it `index`.
