### ISSUE TITLE
import once separate for top level files

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#101]
Two or more non-partial style top level files (filename not starting with an underscore) 
are piped to eyeglass, 
they both @import the same partial style file(s),
import once only allows @import of it in the first top level file.

Example:
styles.scss:
````
@import '_partial';
@debug $variable-defined-in-partial;
````

print.scss:
````
@import '_partial';
@debug $variable-defined-in-partial;
````

Both files are then piped to eyeglass (same gulp.src used).
First file will successfuly debug-print the value of the variable defined in partial file, 
second file will fail as their scopes are isolated and the partial file is not @imported.

So import once needs to maintain a separate @import list/tree per top level style file.

Thank you and
With best regards

**Comment by eoneill** [comment]
This is already fixed in master with #89. This will be in the next release of eyeglass (0.8.0).
