### ISSUE TITLE
eyeglass.assets (.addSource) doesn't exist anymore

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#106]
eyeglass.assets apparently doesn't exist anymore in new API:
````
var Eyeglass = require('eyeglass');
var sassOptions = {};
var eyeglass = Eyeglass(sassOptions);
eyeglass.assets.addSource(assetsDir, {
  globOpts: { ignore: ['**/*.js', '**/*.scss'] }
});
[...]
````
````
[...]
TypeError: Cannot read property 'addSource' of undefined
[...]
````

Thank you and
with best regards

**Comment by eoneill** [comment]
To use the `assets` interface, you need an instance of Eyeglass.

That is, instead of `Eyeglass(sassOptions)`, you should use `new Eyeglass(sassOptions)`

If you don't invoke with `new`, it will wrap the options and return the options object, not the instance.

**Comment by strarsis** [comment]
Thanks.
It may be helpful adding an actualized example to the docs.
