### ISSUE TITLE
Eyeglass needed version

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#109]
Concerning this issue: https://github.com/at-import/breakpoint/issues/152#issuecomment-162068909

What are the best practices for eyeglass versions?
Pick the last eyeglass release and test whether it works - then indicate it as the needed version?
Using a semver range for the patch level?

Thank you and
with best regards

**Comment by chriseppstein** [comment]
The project is just using eyeglass to distribute sass files, the `needs` version can be `*`.
