### ISSUE TITLE
handle renderSync for functions

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#11]
need to test for the presence of the `done()` function.

**Comment by Jakobo** [comment]
After working through the `node-sass` code I wanted to fill this bug in a bit.

When writing a custom importer for `node-sass` / `eyeglass`, the importer can be either sync or async. `node-sass` automatically treats the entire operation as if it was asynchronous. [L#203 node-sass](https://github.com/sass/node-sass/blob/master/lib/index.js#L203) shows the behavior.

Custom functions do not share this behavior. Instead, there is a different code path for `render` and `renderSync` ([render](https://github.com/sass/node-sass/pull/644/files#diff-6d186b954a58d5bb740f73d84fe39073R300), [renderSync](https://github.com/sass/node-sass/pull/644/files#diff-6d186b954a58d5bb740f73d84fe39073R332)).

Asking every developer to create both sync and async pathways increases friction for creating custom eyeglass modules. We instead may want to consider proxying custom functions, always passing `done()` and optionally blocking using a library like [wait.for](https://www.npmjs.com/package/wait.for) when in synchronous mode. This way developers only need to think about their importers and functions in an async manner.

**Comment by chriseppstein** [comment]
I have tests for renderSync and things seem to be working well now.

**Comment by DominicBarnard** [comment]
So can someone clarify, can eyeglass run with renderSync for imports?
The reason I ask is because I'm having trouble getting [sass-true](https://github.com/ericam/true) to work with a project which uses eyeglass to import modules.  sass-true uses renderSync and it seems the eyeglass importer function is loading files in async and is causing test runs to error.  I've made a [minimum test project to demonstrate](https://github.com/DominicBarnard/test-true-eyeglass).
I'm planning to try adding async functionality to sass-true to fix this but just wanted to check I'm on the correct track.

**Comment by Jakobo** [comment]
Yeah, as of commit 57a8ee5762e30f0c19d85fdba8a56dd6aec89746, eyeglass will resolve sync/async items transparently. If we're still stuck, we'll figure out how to make a test case on eyeglass' side.

**Comment by DominicBarnard** [comment]
I'm looking at this now. Possibly narrowed it down to a [bug in node-sass](https://github.com/sass/node-sass/issues/997#issuecomment-110917610).  I think some tests on eyeglass for this will be a good idea since there seems to be a lot of change going on with this feature in node-sass right now.

**Comment by DominicBarnard** [comment]
maybe somthing like https://github.com/DominicBarnard/eyeglass/commit/c830128c59f25175b051c3715da402b48b80f75b

**Comment by DominicBarnard** [comment]
@Jakobo maybe you could take a look at https://github.com/sass/node-sass/pull/1000 and see if I'm missing it, but I can't find a way that importers can do async stuff under `renderSync`.
