### ISSUE TITLE
sass `@import` does not import after eyeglass integration.

### ISSUE THREAD

**Issue by arkhi** [sass-eyeglass/eyeglass#110]
I’m not sure if I’m doing something wrong or if it’s a problem with eyeglass or something else, but as I can’t figure out the why, I’m bringing this up… Maybe it’s related to #85.

With the following directory tree and eyeglass 0.7.1:
```
project
    ├── Gruntfile.js
    ├── package.json
    ├── resources
        ├── assets
            ├── scss
                ├── _base.scss
                ├── _global.scss
                ├── all.scss
                ├── style-guide.scss
```
`Gruntfile.js` contains the following:
```js
module.exports = function( grunt ) {
    var eyeglass = require( 'eyeglass' );
    grunt.initConfig({
        pathSrc: {
            assets: 'resources/assets',
            sass:   '<%= pathSrc.assets %>/scss'
        },

        pathDest: {
            assets: 'public/assets',
            css:    '<%= pathDest.assets %>/css'
        },

        files: {
            scss: [
                '**/*.scss'
            ]
        },
        sass: {
            options: eyeglass.decorate({
                sassDir:     '<%= pathSrc.sass %>',
                imagePath:   'img',
                sourceMap:   true,
                outputStyle: 'compressed'
            }),

            dev: {
                options: eyeglass.decorate({
                    outputStyle: 'expanded'
                }),

                files: [{
                    expand: true,
                    cwd:    '<%= pathSrc.sass %>',
                    src:    [ '<%= files.scss %>' ],
                    dest:   '<%= pathDest.css %>',
                    ext:    '.css'
                }]
            },
        }
    });
};
```

I `@import` both `_base.scss` (settings, functions, mixins…) and `_global.scss` (global styles) in `all.scss` and `style-guide.scss`:
```scss
@import 'base';
@import 'global';
```
with the following in Gruntfile.js, I have an error about a missing mixin (`rem-fb`, rem fallback):
```
>> no mixin named rem-fb
>> 
>> Backtrace:
>> 	resources/assets/scss/_global.scss:27
>>   Line 27  Column 14  resources/assets/scss/_global.scss
```

- Commenting `@import 'global';` from one of the files will not trigger this error.
- Removing eyeglass from the sass task will not trigger this error.

Could that be a bug?

**Comment by eoneill** [comment]
This is a know bug (see #65 #42). This was fixed with #89. This will be in the next release (0.8.0).

The workaround is to disable import-once in eyeglass:

```js
var Eyeglass = require("eyeglass").Eyeglass;
var eyeglass = new Eyeglass({
    sassDir:     '<%= pathSrc.sass %>',
    imagePath:   'img',
    sourceMap:   true,
    outputStyle: 'compressed'
});

eyeglass.enableImportOnce = false;
```

Then pass `eyeglass.sassOptions()` in your grunt config.

**Comment by arkhi** [comment]
@eoneill: Sorry for the noise and thanks for the workaround!

**Comment by eoneill** [comment]
No worries. Thanks for checking out eyeglass and being proactive with your concerns. We're working to get things cleaned up a bit and the next release should be pretty awesome.
