### ISSUE TITLE
Environment variable/detection

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#111]
As functions in eyeglass may be used that are not be available in ruby sass or plain sass, 
it would be useful to offer a way for native sass styles to detect what environment it is running in.
Using this approach, sass styles that don't run in eyeglass can still fall back to either an alternative native sass implementation, show a warning or even gracefully skip the feature.

Thank you and
with best regards

**Comment by eoneill** [comment]
This isn't something we want to support in eyeglass. We recommend using feature detection rather than simply checking which environment you're in. Use `feature-exists`, `function-exists`, `mixin-exists`, and `variable-exists`.
