### ISSUE TITLE
Only changed files/caching

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#113]
Is there a mechanism/an overview in eyeglass, 
the underlying node-sass or libsass that caches 
and processes only files that were changed?

Is this something that gulp-changed or gulp-newer is intended for?
How could one handle complex import/dependency scenarios?

Thank you and
With best regards

**Comment by jackw** [comment]
I don't believe libsass, node-sass nor eyeglass offer the functionality you're looking for. I also think it's something the task system (i.e. gulp / grunt / whatever) should be handling.
Based on your question I assume you're using gulp. Take a look at these two npm modules - I've had great success with them.

https://www.npmjs.com/package/gulp-progeny
https://www.npmjs.com/package/gulp-cached

**Comment by chriseppstein** [comment]
After compiling a file in node-sass, a list of all imported files are available. This can be used to build a dependency tree for caching by the build system. AFAIK, nothing Eyeglass does would break that feature of node-sass as we are simply using the node-sass public APIs for importing files.

this is a good feature to have, but @jackw is right, it's not an eyeglass thing.
