### ISSUE TITLE
Code broke after change from 0.8.0 -> 0.8.1

### ISSUE THREAD

**Issue by Kicu** [sass-eyeglass/eyeglass#119]
Hello, I use eyegalss with gulp, using what (I think is) pretty simple setup.
```
gulp.task('sass', function() {
    return gulp.src('./src/sass/main.scss')
        .pipe(sass(eyeglass(nodeSassOpts)).on('error', sass.logError))
        .pipe(gulp.dest('./dist/css'))
        .pipe(livereload());
});
```
And my code worked good on version 0.8, but with the latest change it doesn't work.
It's trying to load the file 'index.js' from my root directory, which i don't include anywhere and since there is no such file it fails.
I don't know what the problem might be, yet i see in newest commits that there were some changes regarding file reading.

I double checked that sass alone (without eyeglass) compiles without problems, and that the problem occurs only on 0.8.1 and not on 0.8.0

**Comment by eoneill** [comment]
Do you have a `"main": "index.js"` in your project's `package.json`?

**Comment by eoneill** [comment]
For record keeping. This bug was probably introduced in https://github.com/sass-eyeglass/eyeglass/commit/fdabb1a4131183d9765726b279e0b3ff4cb458f2

The fix is probably to check `isEyeglassModule` before we `require(moduleMain)` in [EyeglassModule](https://github.com/sass-eyeglass/eyeglass/blob/master/lib/util/eyeglass_module.js#L28).

**Comment by Kicu** [comment]
@eoneill Yup, actually i do have `"main":"index.js"` in my package json. However it seems that you've figured the issue already ;) 
Thanks

**Comment by eoneill** [comment]
Thanks for confirming! You can probably safely remove that entry to unblock until we get a release out (shouldn't be too long).
