### ISSUE TITLE
assets.httpPrefix should not change the install directory

### ISSUE THREAD

**Issue by georeith** [sass-eyeglass/eyeglass#121]
Assets either need their own buildDir or fallback on the main buildDir, httpPrefix should not be modifying my install location because eyeglass does not know how my routing works.

**Comment by chriseppstein** [comment]
> httpPrefix should not be modifying my install location because eyeglass does not know how my routing works.

We don't, which is why we provide the `installer` callback function. If the default scheme doesn't work for your application, that is how you make sure the file gets put into the right location to be served to the given url.
