### ISSUE TITLE
Minor caveat for the docs?

### ISSUE THREAD

**Issue by mattidupre** [sass-eyeglass/eyeglass#122]
Any Eyeglass module that is required _must_ be listed in that project's package.json. Significant for those of us lazy folks that just shimmed in an ```npm link```ed folder.

I would imagine that there are at least a few others who might try Eyeglass this way and lose a few frustrating hours. In hindsight it seems obvious, of course.

Awesome stuff, by the way. Very excited to see where it goes.

**Comment by chriseppstein** [comment]
fixed by d451e0e.
