### ISSUE TITLE
How do I import assets from another module.

### ISSUE THREAD

**Issue by georeith** [sass-eyeglass/eyeglass#124]
> No assets specified for eyeglass plugin x

There is nothing in the documentation about how to actually expose assets from your module to something else, it tells you how to build assets from your current module. But how do I import a module and let it tell me where its assets are?

The assets build fine from within the module, but when importing the module nada. Am I meant to expose something in `eyeglass-exports.js`?

**Comment by georeith** [comment]
Right after experimentation I have found the following works. The documentation never mentions you are supposed to return an instance of eyeglass in `eyeglass-exports.js` it actually shows returning a plain object, which is wrong because it throws tons of errors when setting assets in there as it attempts to use the prototypical functions on `eyeglass`

**eyeglas-exports.js**:
```js
var path = require("path"),
    rootDir = __dirname,
    assetDir = path.join(rootDir, "assets");

module.exports = function(eyeglass, sass) {
    eyeglass.assets.addSource(assetDir, {
      pattern: "images/**/*"
    });
    return eyeglass;
};
```

**Comment by eoneill** [comment]
You're not supposed to return the `eyeglass` instance. You should be returning a plain Object with an `assets` property. This will look something like...

```js
var path = require("path"),
    rootDir = __dirname,
    assetDir = path.join(rootDir, "assets");

module.exports = function(eyeglass, sass) {
  return {
    assets: eyeglass.assets.export(assetDir)
  };
};
```
