### ISSUE TITLE
Eyeglass modules not discovered if used as peerDependency

### ISSUE THREAD

**Issue by archnode** [sass-eyeglass/eyeglass#126]
If I use an eyeglass module solely as a peer dependency in the projects package.json, the module won't get included properly. Adding the same package as a regular dependency fixes the problem.

It would be great if peerDependencies could have the same behavior as other dependencies.

Thanks for your work on this!

**Comment by eoneill** [comment]
@chriseppstein what are your thoughts? I think this makes sense.

Open question: do we treat `peerDependencies` like normal `dependencies`, or do we treat them like `devDependencies`? That is, do we only look at `peerDependencies` for the top-level (root)?

**Comment by eoneill** [comment]
I think the right call is to always include `peerDependencies` even in sub-modules. Discuss in #127
