### ISSUE TITLE
can't import from node_modules

### ISSUE THREAD

**Issue by j0hnsmith** [sass-eyeglass/eyeglass#130]
I've followed the instructions to use eyeglass with grunt & grunt-sass
https://github.com/sass-eyeglass/eyeglass#example-integration-with-grunt-and-grunt-sass

My config is exactly the same as the readme, eg
```
...
var eyeglass = require("eyeglass");
...
sass: {
    options: eyeglass({sourceMap: true}),
    dist: {
        files: {
            'public/css/main.css': 'sass/main.scss'
        }
    }
}
...
```
I'm getting the error
```
Could not import {my_module}/main.scss from any of the following locations:
...
```

All the locations are in my project, none of them are in `node_modules`. Is this expected?

**Comment by eoneill** [comment]
Is `{my_module}` declared as a `dependency` in your `package.json`?

**Comment by j0hnsmith** [comment]
yes, and it's in `node_modules`

**Comment by eoneill** [comment]
You can try enabling eyeglass debugging when running your command. e.g if your command was `gulp sass` you could run `DEBUG=eyeglass* gulp sass`.

This should log which modules are discovered and should also log some information regarding module imports.

**Comment by j0hnsmith** [comment]
The problem was that the directory where my `main.scss` was outside the directory where `node_modules` is.
