### ISSUE TITLE
Eyeglass doesn't expose private modules to node-sass

### ISSUE THREAD

**Issue by w1p30u7** [sass-eyeglass/eyeglass#131]
Using version 0.8.3 of eyeglass, when I create a private eyeglass module and run the appropriate gulp task(gulp file below), the gulp task returns an error via node-sass(below), and it fails to import in my.scss, and looks like it's not being exposed to sass in the object returned by eyeglass... I haven't logged anything on the node-sass side, but that will be my next step. 

To confirm this wasn't some other config issue, I tried renaming the eyeglass-module package.json from "@w1p30u7/eyeglass-heading" to "eyeglass-heading," and it worked.  Eyeglass can see the module, because it barks at me for using a wildcard for eyeglass version.  I copied the sample-eyeglass package, and tried that too, and had the same results: private doesn't work, but public works fine.  

It's possible that I have some config that's wrong, but my gulp configuration is about as vanilla as you can get in this case. 

I'll give as much info here as I can:

Error
```
Message:
    app/scss/my.scss
Error: Could not import @w1p30u7/eyeglass-heading from stdin
        on line 2 of stdin
>> @import "@w1p30u7/eyeglass-heading";
```

gulp version 3.9.1
```
/*** gulpfile.js ***/
var gulp = require("gulp");
var path = require("path");
var sass = require("gulp-sass");
var eyeglass = require("eyeglass");
var assetsDir = path.join(__dirname, "assets");

var sassOptions = {
  eyeglass: {
    assets: {
      sources: [{
        directory: assetsDir,
        pattern: "images/**/*.png"
      }]
    },
    buildDir: path.join(assetsDir, "images"),
    httpRoot: "../images"
  }
}; 

gulp.task("sass", function () {
  gulp.src("./app/scss/**/*.scss")
    .pipe(sass(eyeglass(sassOptions)).on("error", sass.logError))
    .pipe(gulp.dest("./css"));
});

gulp.task('default', ['sass']);
```

**Comment by w1p30u7** [comment]
@chriseppstein here is a more simplified test case: https://github.com/w1p30u7/private-module-error

**Comment by eoneill** [comment]
Thanks for reporting.

This happens because we split the import path on `/` and use the first piece as the module name:
https://github.com/sass-eyeglass/eyeglass/blob/master/lib/module_importer.js#L87

This might be complex to fix properly (e.g. fully supporting scoped npm package names as import names), but we can probably add validation that throws an exception if the module name contains a slash in it (until we can fix this properly). We already have a check that the module name does not end with `.css` or `.scss`

**Comment by eoneill** [comment]
Also, a workaround to unblock you is to set an eyeglass specific name in your module's `package.json`.

e.g.
```
{
  "name": "@w1p30u7/eyeglass-heading",
  "private": true,
  ...,
  "eyeglass": {
    "name": "@w1p30u7-eyeglass-heading"
  }
}
```

Then you would `@import "@w1p30u7-eyeglass-heading"`

**Comment by w1p30u7** [comment]
@eoneill Thanks so much for responding quickly!  Interesting... yea, looking more in depth that makes sense.  And, it looks like the naming function is an easy fix, and will do the trick.  

I'll go ahead and close this out for now.
