### ISSUE TITLE
Eyeglass fails to install on Node.js 6 under Travis

### ISSUE THREAD

**Issue by JohnAlbin** [sass-eyeglass/eyeglass#133]
It looks like deasync fails to build on Node.js.

The additions to Eyeglass' .travis.yml file seem to allow deasync to build fine. Which means Travis test for Eyeglass on Node.js _should_ be failing but isn't because of those extras.

However, if you include Eyeglass as a dependency (or devDependency) on a package.json, that projects Travis tests will fail.

Steps to reproduce:
- Create an empty GitHub repo and add a package.json and .travis.yml file:
- Enable Travis tests
- Watch the install fail on deasync with:
```In file included from ../src/deasync.cc:3:0:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```

This install failure doesn't happen on Travis for Node.js 5 or earlier.

package.json:
```
{
  "name": "node-6-eyeglass-test",
  "version": "1.0.1",
  "description": "Test to see if Eyeglass installs under Node.js 6.'",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/JohnAlbin/node-6-eyeglass-test.git"
  },
  "author": "John Albin Wilkins <virtually.johnalbin@gmail.com> (http://john.albin.net/)",
  "license": "GPL-2.0",
  "bugs": {
    "url": "https://github.com/JohnAlbin/node-6-eyeglass-test/issues"
  },
  "homepage": "https://github.com/JohnAlbin/node-6-eyeglass-test#readme",
  "dependencies": {
    "eyeglass": "^0.8.3"
  }
}
```

.travis.yml file:
```
sudo: false
language: node_js
node_js:
  - '6'
script: npm test
```

Example repo: https://github.com/JohnAlbin/node-6-eyeglass-test
Actual Travis failure: https://travis-ci.org/JohnAlbin/node-6-eyeglass-test/builds/126856841

**Comment by chriseppstein** [comment]
This is working now. https://travis-ci.org/sass-eyeglass/eyeglass/builds/157192097
