### ISSUE TITLE
Eyeglass module imported within another eyeglass module

### ISSUE THREAD

**Issue by nathanjessen** [sass-eyeglass/eyeglass#134]
I have a css framework that uses gulp-sass and eyeglass. Within my sass files I import Bourbon as an eyeglass module. Everything works as expected. I have turned this framework into an Eyeglass module so I can import it into other projects since it is the core styles I want for all websites I create.

In a 2nd repository, I have a website that has eyeglass setup. I can import eyeglass modules into my sass files as expected. But when I try to import my css framework things error because the Bourbon import can't be found within. I assume this is because node_modules get created within my website build and not within the css framework like previously.

Is there a setting or work around for something like this?

**Comment by eoneill** [comment]
In your eyeglass module, ensure that you're adding `bourbon` as a `dependency` and not a `devDependency`. Similar to npm behavior, eyeglass will only respect `devDependencies` within the top-level project.

If you already have it setup that way, can you try running your gulp command with the `DEBUG` flag (e.g. `DEBUG=eyeglass* gulp sass`) and report back with the output.

**Comment by nathanjessen** [comment]
This came down to a misunderstanding with the eyeglass.sassDir and eyeglass.exports options in package.json. I put the path to my sass file directly in eyeglass.sassDir instead of the eyeglass-exports.js and changed eyeglass.exports to false. This worked fine within the project itself but caused issues in resolving directory within nested projects.

I'm doing a lot of work with Eyeglass modules in my project now so I may come back with suggestions regarding the documentation of the project.

**Comment by eoneill** [comment]
Hrm, that sounds like a bug on our side. We should resolve `sassDir` relative to the module root (e.g. same dir as `package.json`). I'll see if I can reproduce this locally and look into this. Glad you got it working and sorry for the confusion.
