### ISSUE TITLE
Usage with constructor

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#148]
Using no constructor (new) as shown in [Gulp integration readme in this repository](https://github.com/sass-eyeglass/eyeglass/blob/master/site-src/docs/integrations/gulp.md), 
it is apparently not possible invoking extra methods (like addSource(...)):
```js
var gulp = require("gulp");
var sass = require("gulp-sass");
var eyeglass = require("eyeglass");
var sassOptions = {
  // put node-sass options you need here.
  eyeglass: {
    // put eyeglass options you need here.
  }
}; 

gulp.task("sass", function () {
  gulp.src("./sass/**/*.scss")
    .pipe(sass(eyeglass(sassOptions)).on("error", sass.logError))
    .pipe(gulp.dest("./css"));
});
````

When using the constructor to invoke a new eyeglass instance for invoking methods on, 
how to pass the eyeglass instance to gulp-sass? 
Just passing the eyeglass instance to sass(...) results in issues with importing failing suddenly, include path being ignored.
```js
var gulp = require("gulp");
var sass = require("gulp-sass");
var eyeglass = require("eyeglass");
var sassOptions = {
  // put node-sass options you need here.
  eyeglass: {
    // put eyeglass options you need here.
  }
};

var eg = eyeglass(sassOptions);
eg.assets.addSource('./assets', {
  globOpts: { ignore: ['**/*.js', '**/*.scss'] }
});

gulp.task("sass", function () {
  gulp.src("./sass/**/*.scss")
    .pipe(sass(eg).on("error", sass.logError))
    .pipe(gulp.dest("./css"));
});
````

**Comment by eoneill** [comment]
There are two interfaces for eyeglass. One is a simple function and the other is a constructor.

If you use the function (e.g. `var options = eyeglass(...)`) it will simply return the wrapped Sass options object. You cannot call any other methods on this as it's a plain Object (not an instance).

If you want to call additional methods, you need to use the constructor method (e.g. `var eg = new Eyeglass(...)`. The result is an instance with all the eyeglass methods exposed on it. You would them pass `eg.options` to the gulp task (e.g. `sass(eg.options)`.

Finally, you can pass all of your assets directly to the options without having to use the constructor/`#addSource`. e.g.
```js
var sassOptions = {
  ...
  eyeglass: {
    ...
    assets: {
      sources: [
        {directory: './assets', globOpts: { ignore: ['**/*.js', '**/*.scss'] }}
      ]
    }
  }
};
```
