### ISSUE TITLE
Asset installation?

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#15]
We need to figure out how assets (images, fonts, etc) will get out of npm modules and into a location that is servable for the application.

Currently, my idea is to provide a helper function like `eyeglassAssets(destinationDir)` that would return a map of source files to the desired destination directory. This could then be easily integrated into various build pipelines so that the files are never placed into the application's assets locations like they are with compass.

**Comment by chriseppstein** [comment]
@Jakobo thoughts?

**Comment by eoneill** [comment]
Is it sufficient to have a single `destinationDir`, or should we support exporting assets to multiple directories?

I feel that we will need more than a black-box interface given the needs of varying build tools/requirements.

What about something like...
```js
eyeglassAssets.each(function (asset) {
  // some build config paths...
  var path = config.assetPaths[asset.type] || config.assetPaths['default'];
  asset.copyTo(path).then(function(file) {
    // after copying, you can do something with the final path
    // probably not a major use case, but I can see uses for it
  });
  // you also have the flexibility to add future APIs to interact with `asset` if we find use for them
});
```
You might be able to get away with the following signatures...
```js
eyeglassAssets(String) // a single path to export to
eyeglassAssets(Object) // a mapping of paths to export types to
eyeglassAssets(Function) // each asset is passed through the callback function, do whatever you want with it
```

**Comment by Jakobo** [comment]
I don't know how much "asset management" we want eyeglass to do. I almost
want to put this on the eyeglass-modules and offer an API to

1. Get the configuration from the user (api change to optionally pass a
second parameter to eyeglass() for plugin configuration)
2. Provide a notification means for external systems (such as gulp or
broccoli) when additional files are created by an eyeglass-module

This way, eyeglass remains a platform and doesn't get too opinionated about
where / how assets are moved around in a build

On Friday, March 6, 2015, Eugene ONeill <notifications@github.com> wrote:

> Is it sufficient to have a single destinationDir, or should we support
> exporting assets to multiple directories?
>
> I feel that we will need more than a black-box interface given the needs
> of varying build tools/requirements.
>
> What about something like...
>
> eyeglassAssets.each(function (asset) {
>   // some build config paths...
>   var path = config.assetPaths[asset.type] || config.assetPaths['default'];
>   asset.copyTo(path).then(function(file) {
>     // after copying, you can do something with the final path
>     // probably not a major use case, but I can see uses for it
>   });
>   // you also have the flexibility to add future APIs to interact with `asset` if we find use for them
> });
>
> You might be able to get away with the following signatures...
>
> eyeglassAssets(String) // a single path to export to
> eyeglassAssets(Object) // a mapping of paths to export types to
> eyeglassAssets(Function) // each asset is passed through the callback function, do whatever you want with it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sass-eyeglass/eyeglass/issues/15#issuecomment-77629693>
> .
>


-- 

--Jakob

**Comment by chriseppstein** [comment]
Going to move this conversation over here: https://github.com/sass-eyeglass/eyeglass-assets/issues/1

@eoneill and I had a hallway conversation today and came up with some good ideas. I will post the plan tomorrow for review.
