### ISSUE TITLE
@import fails in simple test eyeglass setup

### ISSUE THREAD

**Issue by morewry** [sass-eyeglass/eyeglass#164]
I am trying to start using eyeglass@1.2.1 and am running into problems where, although eyeglass modules are discovered, `@import`ing them fails.

Here is the gulp task (only wrapped with gulp at this point because I don't know how to get pretty eyeglass debug output otherwise) which uses node-sass to compile a single file.

```js
gulp.task('sass', () => {
  const options = eyeglass({
    file: path.join('test', 'test.scss'),
    engines: {
      sass: nodeSass
    }
  });
  return nodeSass.render(options, (err, result) => console.log(err, result));
});
```

```
eyeglass:modules discovered modules
eyeglass:modules 	:root(test)
eyeglass:modules 	├── eyeglass@1.2.1
eyeglass:modules 	├── eyeglass-sample@0.0.3
eyeglass:modules 	└── true@2.2.1
eyeglass:modules 	 +0ms
eyeglass:functions functions discovered in module eyeglass:
• eyeglass-asset-uri($registered-assets, $relative-path)
• eyeglass-normalize-uri($uri, $type: web)
• eyeglass-uri-preserve($uri)
• eyeglass-uri-restore($uri)
• eyeglass-version($module: eyeglass)
• eyeglass-fs-absolute-path($fs-registered-pathnames, $path-id, $segments...)
• eyeglass-fs-join($segments...)
• eyeglass-fs-exists($absolute-path)
• eyeglass-fs-path-separator()
• eyeglass-fs-list-files($directory, $glob: '*')
• eyeglass-fs-list-directories($directory, $glob: '*')
• eyeglass-fs-parse-filename($filename)
• eyeglass-fs-info($filename)
• eyeglass-fs-read-file($filename) +13ms
eyeglass:functions functions discovered in module eyeglass-sample:
• hello($name) +1ms
eyeglass:functions all discovered functions:
• eyeglass-asset-uri($registered-assets, $relative-path)
• eyeglass-normalize-uri($uri, $type: web)
• eyeglass-uri-preserve($uri)
• eyeglass-uri-restore($uri)
• eyeglass-version($module: eyeglass)
• eyeglass-fs-absolute-path($fs-registered-pathnames, $path-id, $segments...)
• eyeglass-fs-join($segments...)
• eyeglass-fs-exists($absolute-path)
• eyeglass-fs-path-separator()
• eyeglass-fs-list-files($directory, $glob: '*')
• eyeglass-fs-list-directories($directory, $glob: '*')
• eyeglass-fs-parse-filename($filename)
• eyeglass-fs-info($filename)
• eyeglass-fs-read-file($filename)
• hello($name)
[19:25:56] Finished 'sass' after 97 ms
eyeglass:import true can be imported from ~/eyeglass-test/test/test.scss +5ms
{ [Error: Error: Could not import true from any of the following locations:
  ~/eyeglass-test/test/true.scss
  ~/eyeglass-test/test/true.sass
  ~/eyeglass-test/test/true.css
  ~/eyeglass-test/test/_true.scss
  ~/eyeglass-test/test/_true.sass
  ~/eyeglass-test/test/_true.css
  ~/eyeglass-test/test/true/index.scss
  ~/eyeglass-test/test/true/index.sass
  ~/eyeglass-test/test/true/index.css
  ~/eyeglass-test/test/true/_index.scss
  ~/eyeglass-test/test/true/_index.sass
  ~/eyeglass-test/test/true/_index.css]
  status: 1,
  file: '~/eyeglass-test/test/test.scss',
  line: 1,
  column: 9,
  message: 'Error: Could not import true from any of the following locations:
    ~/eyeglass-test/test/true.scss
    ~/eyeglass-test/test/true.sass
    ~/eyeglass-test/test/true.css
    ~/eyeglass-test/test/_true.scss
    ~/eyeglass-test/test/_true.sass
    ~/eyeglass-test/test/_true.css
    ~/eyeglass-test/test/true/index.scss
    ~/eyeglass-test/test/true/index.sass
    ~/eyeglass-test/test/true/index.css
    ~/eyeglass-test/test/true/_index.scss
    ~/eyeglass-test/test/true/_index.sass
    ~/eyeglass-test/test/true/_index.css',
      formatted: 'Error: Error: Could not import true from any of the following locations:
    ~/eyeglass-test/test/true.scss
    ~/eyeglass-test/test/true.sass
    ~/eyeglass-test/test/true.css
    ~/eyeglass-test/test/_true.scss
    ~/eyeglass-test/test/_true.sass
    ~/eyeglass-test/test/_true.css
    ~/eyeglass-test/test/true/index.scss
    ~/eyeglass-test/test/true/index.sass
    ~/eyeglass-test/test/true/index.css
    ~/eyeglass-test/test/true/_index.scss
    ~/eyeglass-test/test/true/_index.sass
    ~/eyeglass-test/test/true/_index.css
  on line 1 of test/test.scss
  >> @import "true";
     --------^
  ' } null
```

I've tried this with several potential eyeglass dependencies, e.g.

- eyeglass-sample
- eyeglass-math
- susy
- true

I get the same type of failure for all of them, where they appear to be available in debug output, but attempting to `@import` them by name or `@import` anything in their `sass` directories fails.

I get these failures even when very specific messages that say things are importable show up:

```
eyeglass:import susy can be imported from ~/eyeglass-test/sass/_test.scss +14ms
...
Error: File to import not found or unreadable: susy.
```

If I start from scratch again, I run into this, which I've gotten past (though I don't remember how):

```
> DEBUG=* gulp sass
[12:51:50] Requiring external module babel-register
[12:51:53] Using gulpfile ~/Projects/eyeglass-test/gulpfile.babel.js
[12:51:53] Starting 'sass'...
  eyeglass:modules discovered modules
  eyeglass:modules 	:root(eyeglass-test)
  eyeglass:modules 	├── eyeglass@1.2.1
  eyeglass:modules 	└── susy@2.2.12
  eyeglass:modules 	 +0ms
[12:51:53] 'sass' errored after 29 ms
[12:51:53] TypeError: this.main is not a function
    at EyeglassModule.init (~/eyeglass-test/node_modules/eyeglass/lib/modules/EyeglassModule.js:80:33)
    at ~/eyeglass-test/node_modules/eyeglass/lib/modules/EyeglassModules.js:83:9
    at Array.forEach (native)
    at EyeglassModules.init (~/eyeglass-test/node_modules/eyeglass/lib/modules/EyeglassModules.js:82:13)
    at new Eyeglass (~/eyeglass-test/node_modules/eyeglass/lib/index.js:35:16)
    at Eyeglass (~/eyeglass-test/node_modules/eyeglass/lib/index.js:18:13)
    at Gulp.<anonymous> (~/eyeglass-test/gulpfile.babel.js:7:19)
    at module.exports (~/eyeglass-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (~/eyeglass-test/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (~/eyeglass-test/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

The above are the most simplified cases for illustration purposes. I have tried this using alternatives from issues such as `new Eyeglass` and `eyeglass.Eyeglass` and `eyeglass.sassOptions()`. I have tried it with and without `enableImportOnce: false`.  I've tried manually adding the modules via the eyeglass options.  I have tried it with and without `engines`. I have tried it with and without providing a default `importer` as mentioned in other issues. I've tried it using node-sass, gulp-sass, and true's runner method (through which true but nothing else can be imported because true adds itself to `includePaths`).

The only thing I have _not_ tried--although I am very sure it will work--is manually creating my own `includePaths` configuration to include the sass directories of the eyeglass modules, because not having to do that is one of two reasons I'm interested in using eyeglass. I'd gotten the impression that _typically_ it isn't supposed to be necessary to set up `includePaths` to use eyeglass modules, but, assuming it's caused by something I'm doing, it's not clear to me what inevitable common circumstance I've created in all of these various attempts that has consistently required my doing so.

Cross posted to http://stackoverflow.com/questions/42564148/why-cant-files-from-sassdir-of-discovered-eyeglass-modules-be-imported

**Comment by morewry** [comment]
I was able to reproduce this several times, but had to put it down for a bit. When I came back to it and set up individual examples for the various things I tried, I discovered that I had gotten further than I'd thought and my main issues were:

1. True is unique.
2. Eyeglass doesn't support transitive dependencies.

Here are all the examples I ultimately created for troubleshooting, in case they are useful to others.

https://github.com/morewry/sass-eyeglass-examples

**Comment by eoneill** [comment]
Thanks for reporting this and for the detailed examples. Sorry I didn't look into this sooner.

The root issue you were running into with `true` is that it is not correctly configured as a an eyeglass module. It's missing `sassDir`, so eyeglass isn't able to correctly resolve the path to `_true.scss`.

I've opened a PR against `true` that should resolve this going forward. Eyeglass could probably use some better logging here to make this more obvious.

**Comment by eoneill** [comment]
Also, the `devDependencies` behavior was intentional, to more closely mimic the behavior of `dependencies`/`devDependencies` in node.

**Comment by morewry** [comment]
> Also, the devDependencies behavior was intentional, to more closely mimic the behavior of dependencies/devDependencies in node.

Yes, that makes sense--definitely business as usually with npm modules, as I should have realized.
