### ISSUE TITLE
Incompatible dependencies needs: "The following modules are incompatible with eyeglass" error

### ISSUE THREAD

**Issue by mdentinho** [sass-eyeglass/eyeglass#165]
Hi guys,

I've created an eyeglass module that `"needs": "^1.2.1"` to use on other projects.

One of this projects has also `bootstrap-sass` as a dependency, which has eyeglass support (that was not being used, since the project hadn't eyeglass configured).

After installing the eyeglass module (1.2.1) and configured it on the project, the build script started to throw this error:
```bash
The following modules are incompatible with eyeglass 1.2.1:
  bootstrap-sass needed eyeglass ^0.7.1
```

Basically, `bootstrap-sass` needs any `0.x.x`, but none major release above that (1.x.x).

Since I couldn't find any information on handling incompatible dependency `needs`, I'd like to know if/how it is possible to configure it.

My environment:
OS: macOS 12.12.3
Node: 7.8.0
NPM: 4.2.0

Some project infos:
Webpack: 2.3.2
sass-loader: 6.0.3
Eyeglass: 1.2.1

Thanks!

**Comment by eoneill** [comment]
This is more of a warning than an error. It won't cause your build to fail, but it just warns you about potential incompatibilities. The good news is, there have been very few breaking changes between `0.7.1` and `1.2.1`, so you probably won't have any issues using `bootstrap-sass` as-is.

However, if this warning concerns you still, you can submit a pull request to [bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/master/package.json#L42) to bump the `needs` to `^1.0.0`.

**Comment by mdentinho** [comment]
Thank you for the reply @eoneill.

I've actually posted the issue because the build was failing, but with your comment I check a little deeper and found the real reason for that (which had nothing to do with eyeglass).

Closing this. ;)

**Comment by mrmartineau** [comment]
@mdentinho would you mind telling us what your solution was? I only ask because I am also getting this error with the [modularscale-sass](https://github.com/modularscale/modularscale-sass/issues/141) package.

Thanks
