### ISSUE TITLE
Create repo of eyeglass frameworks, call each one a lens

### ISSUE THREAD

**Issue by micahgodbolt** [sass-eyeglass/eyeglass#17]
Ruby has gems, Eyeglass should have lenses. I don't want to install an eyeglass, I want to install a lens.

**Comment by acdlite** [comment]
@micahgodbolt The "lenses" are npm modules: https://github.com/sass-eyeglass/eyeglass#writing-an-eyeglass-module-with-custom-functions

**Comment by micahgodbolt** [comment]
ahh, good point. no need for seperate repository. Ok, I just want to coin the term lens for a Sass NPM module :D

**Comment by acdlite** [comment]
I could get behind that :D

**Comment by chriseppstein** [comment]
it's clever. but yeah, I don't think we need a special name here.
