### ISSUE TITLE
Is there any way of using eyeglass in a Ruby on Rails project?

### ISSUE THREAD

**Issue by RandieM** [sass-eyeglass/eyeglass#176]
I have been very happily using Compass in my Ruby on Rails projects, but I have to move away from it, for obvious reasons. Now, excuse my ignorance, as I have no clue about node modules, but is there any way at all that I can use eyeglass with Rails?

**Comment by ArmorDarks** [comment]
It is made to work particularly with NPM and revolves around Node ecosystem, so I don't think that it will be ever possible.

**Comment by RandieM** [comment]
Thanks @ArmorDarks for your input. Judging from @chriseppstein's thumbs-up reaction to your post, I suppose I can now close this issue.
