### ISSUE TITLE
Better Errors when imports fail

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#2]
See also: https://github.com/sass/node-sass/issues/651

We need to give better errors when imports from node modules fail.

**Comment by Jakobo** [comment]
At a minimum, a proper node module won't install/link correctly, so when working outside of test data the problem we encountered is less likely to happen. In the future `npm init` should provide a package.json with sufficient scaffolding for tests.

**Comment by chriseppstein** [comment]
@Jakobo This sounds like a good change. Do you have time to submit the patch for it?

**Comment by Jakobo** [comment]
Yeah. I'll have some time today to improve it so we can drop the node-resolve dependency.

--Jakob/mobile




On Mon, Feb 9, 2015 at 9:33 AM -0800, "Chris Eppstein" <notifications@github.com> wrote:












@Jakobo This sounds like a good change. Do you have time to submit the patch for it?

**Comment by chriseppstein** [comment]
FWIW, when I wrote this bug I was more concerned about handling typos like `@import "<molude_a>"` and being able to return an error like `Could not find npm module <molude_a> did you mean one of "module_a", "module_b", or "module_c"?`

**Comment by chriseppstein** [comment]
Node-sass fixed this, but we removed our ability to return detect import errors in the meantime :P
