### ISSUE TITLE
Reasons for using 'sass' as the load path folder?

### ISSUE THREAD

**Issue by BPScott** [sass-eyeglass/eyeglass#20]
Hi Chris, thanks for your work so far on eyeglass.

I was wondering about the reason for using `sass` as the name of the folder in that get's added to node-sass's load path? To me it would make more sense to follow the convention that compass uses - which is to use the [`stylesheets` folder](http://compass-style.org/help/tutorials/extensions/) (why am I linking you to this page, you wrote the dang thing...).

This would allow existing compass extensions that are pure Sass (and compile in both Ruby Sass and libsass) to be referencable through eyeglass without needing to create duplicate files within their repositories.

For a bit of context, I maintain [Breakup](https://github.com/BPScott/breakup), a Sass utility which is packaged as a Compass extension for convenience of developer consumption through RubyGems. As it is essentially a single Sass file that uses long-supported features it is also compatible with libsass, so I have also packaged it and placed in on npm. If eyeglass used the `stylesheets` folder then Breakup would "just work":tm: and people could `@import "<breakup-sass>/breakup";`. However as eyeglass currently uses the `sass` folder I would need to create a duplicate of `stylesheets/_breakup.scss` in the `sass` folder and keep these two files in sync.

Would you consider changing from `sass` to `stylesheets` to help consistency and save on this potential for duplication?

**Comment by Jakobo** [comment]
Hi! You can actually get the functionality you are looking for via the ` eyeglass-exports.js` file. 

```js
"use strict";

var path = require("path");

module.exports = function(eyeglass, sass) {
  return {
    sassDir: path.join(__dirname, "stylesheets")
  }
};
```

Separately, @chriseppstein thoughts about following compass' convention in the readme so there is consistency for those familiar with the compass project?

**Comment by BPScott** [comment]
Hi @Jakobo,

Thanks for that, it's even in the readme, so that's a total fail of my reading comprehension (note to self: don't GitHub just before bedtime). Sorry about that.

**Comment by Jakobo** [comment]
No worries :) I think there is a valid convention question we should 2x check with Chris on. We definitely want people coming from compass to feel at home.

**Comment by chriseppstein** [comment]
The default directory for projects used to be "stylesheets" and so extensions used "stylesheets" as well. Later, people wanted it to be "sass" so I moved it over for applications, but I never changed extensions' conventions to match. Defaulting to sass is just finishing a transition that I should have but never completed in compass.

In compass, the stylesheets directory is also configurable, so really you can go with either location and just tell the other one what directory to use. Sorry they are not the same default, but I like "sass" better these days.

**Comment by BPScott** [comment]
Thanks for the clarification @chriseppstein. In that case I'll move my folder over to `sass` and make use of the new hotness in naming conventions (fwiw, I prefer `sass` to `stylesheets` too).

**Comment by polarathene** [comment]
@chriseppstein At the start of this [doc](https://github.com/sass-eyeglass/eyeglass/blob/master/docs/eyeglass_modules/index.md), the structure lists a `scss` folder, should it be `sass` or has it since changed?
