### ISSUE TITLE
Custom Functions proxied into node-style callbacks

### ISSUE THREAD

**Issue by Jakobo** [sass-eyeglass/eyeglass#23]
Correctly (the Sass way), custom functions return a `sass.types.Error` object when they encounter errors. However, that is not very node-like. Instead, we should probably be proxying the function, use `wait.for`, and make the callbacks in eyeglass behave as if they are truly node async functions. This means:

1. Automatically provide a `done()` callback if one doesn't exist
2. Intelligently use `wait.for` to block async resolution in `renderSync` mode (no `done` callback incoming)
3. Provide an alternate node-friendly `done()` to the custom function that will take any error object from `done(error, null)` and properly class it into a `sass.types.Error` object.

**Comment by chriseppstein** [comment]
@Jakobo is there still something needed for this?

**Comment by chriseppstein** [comment]
I think this is handled.
