### ISSUE TITLE
Consider a configuration file

### ISSUE THREAD

**Issue by pascalduez** [sass-eyeglass/eyeglass#25]
Greetings,

is there any plans on adding a configuration file feature ?

Something like an `.eyeglassrc` that would only be found at a project root, and would allow to share configuration keys between modules.

Alternatively it could make use of `package.json` but I tend to lean towards a separate file.

The [js-yaml](https://github.com/nodeca/js-yaml) package can bring both JSON and YAML support out of the box.

One (of the many) great features of Compass is its [`config.rb`](http://compass-style.org/help/documentation/configuration-reference/) file. So that project wide configuration (paths, dirs, urls, cache, ...) can be set in one place and shared between libraries.

**Comment by chriseppstein** [comment]
@pascalduez First, we are focusing on enabling configuration via various build tools using a javascript API. So the configuration would be shared via the configuration file specific to grunt, gulp, broccoli, etc.

Similarly, we don't provide an executable at this time as the build tool UI is preferred.
