### ISSUE TITLE
Are angle brackets the right syntax to use when referring to a node module?

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#26]
Following up from this comment: https://github.com/sass-eyeglass/eyeglass/pull/22#issuecomment-83715481

/cc @ericam @aaronagray

**Comment by aaronagray** [comment]
Thanks for looping me in. I agree that the current format will be confusing to most. 

How about something that looks more like Ruby / ES6 string interpolation? 

```
@import "#{my_file_name}/file";
```

**Comment by chriseppstein** [comment]
I'm hesitant to do that because it's standard sass syntax for escaping to sassscript and users will think they can use variables in there, etc.

An idea I had was `@import "~foo/bar.png";` which is borrowing from the unix "home directory" syntax, which may also be a bad idea.

**Comment by aaronagray** [comment]
I'm not a fan of using `~` here because it's not clear where the module name and path begin.

It seems like there are three approaches to this:

1. Wrap the module name in two identifiers (ie < & >)
2. Begin the string with a non-standard path character
3. Split the string on a non-standard path character

My preference is 1 or 3. Am I missing any alternatives?

Also, I updated my comment above to include ES6 example. Does changing that example to use `$` instead of `#` mitigate your concerns about the sassscript association? Would something else entirely work better (`~{file_name}`)?

Here are a couple other ideas that use the 3rd approach:

```
@import "susy:susyone";
```

```
@import "susy@susyone";
```
We could split the string on either of these characters to determine the module name and path as needed.

**Comment by ericam** [comment]
Another, more verbose option would be a function syntax: `plugin(foo)`. Not sure that's the right association either — it actually makes me just want the ability to interpolate import strings. :)

**Comment by ericam** [comment]
@aaronagray What would the base import of susy be in your proposal? If you are not grabbing a nested partial, you lose the delimiter: `@import 'susy';` unless we require a full `@import 'susy:susy';`. (I like `@` less than `:` because I can't tell which side is the plugin, and which side is the path).

**Comment by aaronagray** [comment]
That's a great point, @ericam. 

My understanding is that we need to A) identify the node_module folder name, B) determine which file to expose from there, and C) use something that sasscript won't try to import on its own. Are these accurate constraints @chriseppstein? If so, maybe option 3 (described above) won't work. In which case, I'd like to hear thoughts on using the [ES6 format](http://babeljs.io/docs/learn-es6/#template-strings).

**Comment by eoneill** [comment]
I would like to avoid anything that feels interpolated (e.g. `#{...}` or `${...}`). If they feel like interpolation, I expect interpolation to work (e.g. `@import "my/${dynamic}/file"`).

Instead, I'll propose that we follow a pattern similar to C/ObjectiveC for distinguishing between global vs local includes...
```
#include "example.h"
#include <example.h>
```
These will resolve to different files, where the former is a local include and the latter is a global include.

Granted, in our case, this isn't really global vs local, but we can easily take this to mean that one is _from my code_ and the other is _from external code_.

So I propose that we do...
```scss
@import "foo"; // local `foo`
@import "<foo>"; // external `foo`
...
asset-url("<foo/bar.png>"); // external `foo/bar.png`
```
Note that this proposal wraps the entire path reference in `<...>`, not just the module name, but the module name will be assumed to be the first dirname.

C++ hasn't had any issues documenting the usage of angle bracket includes, so I think we'll be fine :)

**Comment by aaronagray** [comment]
@eoneill, I'm happy with that as long as we explicitely document the usage and include an example like the one you provided above. So many people don't read, apparently, but as long as we're explicit about including the brackets then we could be alright.

**Comment by chriseppstein** [comment]
Another approach: we could be more verbose. That is the CSS way, right?

```scss
@import "module foo";
@import "bar from module foo";
.foo{ background: asset-url("foo.png in module foo");
```

**Comment by ericam** [comment]
That's starting to look more like @nex3's proposal for advanced imports in Sass. That may be a good tie-in.

**Comment by aaronagray** [comment]
@chriseppstein I like this best so far.

**Comment by eoneill** [comment]
I don't like that @chriseppstein :)

It feels like an awkward/broken ES6 import statement.

**Comment by Jakobo** [comment]
I'd like to keep it simple. Perhaps we even err further on the side of npm nomenclature.

* starts with a `.`, it's a relative include
* starts with `/[a-z0-9]/i` it's a node module include

At least then there's no learning curve for people already familiar with node.js and npm. We can also just [refer to those docs](https://nodejs.org/api/modules.html#modules_module_require_id) on module / id resolution.

**Comment by ericam** [comment]
I tend to prefer readable & explicit over short and clever when reasonable, so that's my vote. I also think we should be consistent with the direction of advanced sass imports (if those are still in the plans). I know it can feel bulky to advanced users, but that's what text-editor snippets are for. I don't want to make users look up the node docs to know what a sass import is doing.

**Comment by Jakobo** [comment]
It seems to have a lot to do with our perspective on eyeglass. From the Sass side, the more verbose approach makes sense. From the node side, staying as true as possible to the `require()` logic through either module resolution or some sort of `<`/`>` demarcation makes sense.

Eyeglass has the enjoyable(?) position of sitting squarely between these two worlds. This is probably as much a philosophical discussion as a technical one.

**Comment by scottdavis** [comment]
Just spitballing but.
``` scss
@import "lens foo"; //eyeclass modules are called "len's"
@import "bar from lens foo";

// or maybe supply it as a function to make it more declarative like susy 
lens('foo');
lens("bar from foo");
lens("bar as baz from foo");
lens-asset("bar.png from foo") 
```
I'm more for this verbose sentence style import syntax then I would be for the proposed `@` or `:` Using those in import declarations just seems gross to me from a code readability standpoint and the sentence style is also more declarative.

**Comment by Jakobo** [comment]
#24 I'm just throwing some code up. This would remove the `<` and `>` entirely. It would also allow us to adopt the proposal for advanced imports that @ericam mentioned when Sass => libsass => node-sass adopt it.

At that point, the "eyeglass" importer's job is to automatically check your node modules on your behalf and not much more, falling back to a native Sass import if there is no node.js resolution.

**Comment by chriseppstein** [comment]
Ok, after sleeping on this, I think @Jakobo has the right of it. Even though we are using a custom importer, we should not need any special syntax, the importer simply acts as if we put the eyeglass modules on the load path. The first directory will be checked if it is an eyeglass module and if it is, we import as if it had been wrapped in angle brackets.

**Comment by aaronagray** [comment]
+1. That seems best. I like that we can document this in one place whereas something like angle brackets would require more explanation in more places.

**Comment by Snugug** [comment]
:+1: for @Jakobo's proposal for npm style. It'll also make sure that things written in `node-sass` with Eyeglass have a chance of being compatible with Ruby Sass.

**Comment by chriseppstein** [comment]
This landed on master.
