### ISSUE TITLE
Update README with example for grunt?

### ISSUE THREAD

**Issue by thomasmattheussen** [sass-eyeglass/eyeglass#32]
It might be useful to document somewhere in the README how to use eyeglass with grunt-sass, as it wasn't immediately clear to me. 

I've got it working like this:

```js
sass: {
    options: require("eyeglass")({
        sourceMap: true
    }).sassOptions(),
    dist: {
        files: {
            'public/css/main.css': 'sass/main.scss'
        }
    }
}
```

**Comment by chriseppstein** [comment]
:+1: This is good. Would you care to submit a PR for the README?

**Comment by thomasmattheussen** [comment]
https://github.com/sass-eyeglass/eyeglass/pull/34
