### ISSUE TITLE
Make @import empty

### ISSUE THREAD

**Issue by idflood** [sass-eyeglass/eyeglass#33]
I can't make eyeglass work, maybe it's something related to recent libsass/node-sass updates. My setup involve gulp and sass files but I tried to convert the files to scss too without success.

For reference my gulpfile contains something like this:

    var eyeglass = new Eyeglass(sassOptions, sass.compiler);
    eyeglass.assets("assets/images", "images", "public/images");
    eyeglass.assets("assets/fonts", "fonts", "public/fonts");

    gulp.src('src/*.sass')
      //.pipe(sass(eyeglass.sassOptions()))
      .pipe(sass(sassOptions))
      .pipe(gulp.dest('dist'));

If a sass file contains something like this:

    @import "modules/my_module"
    body
      background: red

The result looks like this:

    body{background: red;}

In fact the problem exist as soon as I create a new instance of `Eyeglass`.

**Comment by idflood** [comment]
The problem might be in gulp-sass instead since if I try with node-sass it works as expected.

**Comment by chriseppstein** [comment]
@Jakobo did you ever figure out how to make gulp integration work?

**Comment by chriseppstein** [comment]
We had some problems with gulp because we need some hook at the start of every new file so we can reset the import-once cache.

broccoli integration is working great though. https://github.com/sass-eyeglass/broccoli-eyeglass

**Comment by idflood** [comment]
I'm not sure this is relevant but gulp-sass use `options.data` instead of `options.file`:
https://github.com/dlmanning/gulp-sass/blob/master/index.js#L33

In module_importer.js the `isRealFile` is always false with gulp and a console.log(prev) just after that return `stdin`.

**Comment by chriseppstein** [comment]
We have a [gulp integration guide](https://github.com/sass-eyeglass/eyeglass/blob/master/docs/integrations/gulp.md). The main thing you need from that is the `eyeglass.enableImportOnce = false` part.

**Comment by idflood** [comment]
I still can't make it to work with eyeglass : /

I've created a test repository showing the problem here: https://github.com/idflood/gulp-eyeglass-test

Eyeglass functions and import works as expected:
- source: https://github.com/idflood/gulp-eyeglass-test/blob/master/src/test4.scss
- output: https://github.com/idflood/gulp-eyeglass-test/blob/master/dist/test4.css

But I still don't have any luck with normal `@import`:
- source: https://github.com/idflood/gulp-eyeglass-test/blob/master/src/test1.scss
- output: https://github.com/idflood/gulp-eyeglass-test/blob/master/dist/test1.css

In test1.css there should be this at the top:

    .sub1 {
      content: "scss file imported";
    }

@chriseppstein Am I doing something wrong?

**Comment by idflood** [comment]
I'm not sure if it helps, but I tried some things in https://github.com/sass-eyeglass/eyeglass/blob/master/lib/module_importer.js#L134

Instead of doing `done(sass.NULL)` I tried `done(uri)`. This make standard `@import` work but it make an error with `list-files` on test4.scss.

**Comment by idflood** [comment]
Thanks to @pnuzhdin the trick to make it work is to pass a fallback importer:

https://github.com/idflood/gulp-eyeglass-test/pull/1
