### ISSUE TITLE
import-once and gulp

### ISSUE THREAD

**Issue by kaelig** [sass-eyeglass/eyeglass#42]
It is a known bug, `import-once` doesn't play well with Gulp.

I've opened this issue to track the resolution of the problem.

**Comment by chriseppstein** [comment]
gulp-sass has other issues as well, for instance it doesn't set the `file` option and so it's impossible to do relative importing to the imported file.

**Comment by mattidupre** [comment]
Is there anything we can do to help with this? It would be nice to have a thread to nail down all the issues with gulp-sass. Or is the issue with gulp instead?

**Comment by strarsis** [comment]
I tried to use this custom importer with eyeglass: https://github.com/at-import/node-sass-import-once

````
[...]
  var eyeglass = new Eyeglass({
    importer: importOnce,
    importOnce: {
      index: true,
      css:   false,
      bower: false
    }
  });
[...]
````

However, the importer isn't able to see the importOnce property in options object, 
is there a way to pass it to the importer when eyeglass is used instead of plain node-sass?

````
/home/build/src/test/node_modules/node-sass-import-once/index.js:275
  if (!this.options.importOnce) {
                   ^

TypeError: Cannot read property 'importOnce' of undefined
    at Object.importer [as fallbackImporter] (/home/build/src/test/node_modules/node-sass-import-once/index.js:275:20)
[...]
````

Actually a nice candidate to have import once with eyeglass/gulp until it has been natively fixed there.

With best regards

**Comment by eoneill** [comment]
@strarsis, can you open a new issue for this, as I think it's a different problem.

**Comment by strarsis** [comment]
Concerning the missing binding of function (https://github.com/sass-eyeglass/eyeglass/issues/83), 
I found a workaround for it using a wrapper:
````
var importOnceOptions = {
    index: true,
    css:   false,
    bower: false
  };
  var importOnceWrap = function(uri, prev, done) {
    var wrap = { options: { importOnce: importOnceOptions } };
    return importOnce.bind(wrap)(uri, prev, done);
  };
  var eyeglass = new Eyeglass({
    importer: importOnceWrap
  });
````

Does this work for you and prevent multiple imports when using eyeglass + gulp?

With best regards

**Comment by chriseppstein** [comment]
The fix for this is merged. Import once should work with gulp in `0.8.0` which is not yet released but will be very soon.

Please don't use `node-sass-import-once` with eyeglass.
