### ISSUE TITLE
(Grunt) includePaths not working

### ISSUE THREAD

**Issue by FransTwisk** [sass-eyeglass/eyeglass#47]
When using eyeglass via Grunt and configuring it as explained in the example, the includePaths don't seem to work. I'm using node-sass@3.2 and grunt-sass@1.0, currently configured as:

```
...
var neat = require('node-neat').includePaths;
var paths = ['./sass/'].concat(neat); // this will also add bourbon

grunt.initConfig({
    ...
    sass: {
      options: require("eyeglass")({
        includePaths: paths,
        sourceMap: true,
        outputStyle: 'compressed'
      }).sassOptions(),
      files: {
        '<%= clientCssOutputPath %>main.css': '<%= clientSassPath %>main-extend.scss',
        '<%= clientCssOutputPath %>ie.css': '<%= clientSassPath %>ie-extend.scss',
      }
});
...
```
I left out some variables and code, but all folders are correct. Getting the following error:
```
Could not import main from any of the following locations: ...
```

The locations it looks in never include the includePath folders. This works if I don't initialise eyeglass via:
```
...
options: {
    includePaths: paths,
    sourceMap: true,
    outputStyle: 'compressed'
},
...
```

**Comment by Jakobo** [comment]
Is the `main` it's trying to import coming from neat/bourbon?

**Comment by FransTwisk** [comment]
No, it's coming from main-extend.scss. It's located in the root of ./sass/

**Comment by alanhogan** [comment]
+1 

I wrote two small example scripts, one using node-sass directly, and one using `eyeglass.sassOptions()` as per the project README.

When using node-sass directly, `includePaths` works perfectly…

When using Eyeglass, it never makes it; the error message makes it clear it isn’t looking in `includePaths`.

This issue is probably the root cause of https://github.com/sass-eyeglass/broccoli-eyeglass/issues/13.

**Comment by alanhogan** [comment]
If your issue is the same as mine, note that I think I have fixed this. I'll be making a PR shortly!

**Comment by alanhogan** [comment]
@FransTwisk Would you mind seeing if this patch solves your problem? I haven’t tried Gulp. https://github.com/sass-eyeglass/eyeglass/pull/51/files

**Comment by JohnRiv** [comment]
I upgraded to 0.6.1 and this pull request appears to be causing an issue now with grunt-sass. includePaths is coming through as an array now, so the call to `split` results in `Fatal error: Cannot read property 'split' of undefined`

Also, if includePaths isn't included as an option, it fails with `Fatal error: Cannot read property 'forEach' of undefined`

@alanhogan @FransTwisk can you confirm the same thing I'm seeing?  I'll try to get it working myself and submit a new pull request.

**Comment by chriseppstein** [comment]
This should all be working now.

Side-note: node-neat should be an eyeglass module :)
