### ISSUE TITLE
Circular reference in sassOptions breaks Grunt

### ISSUE THREAD

**Issue by mikl** [sass-eyeglass/eyeglass#52]
In this commit, a reference to the Eyeglass object is made inside the options object https://github.com/sass-eyeglass/eyeglass/commit/9479bbfb45ae70b07be3b77f884ce588491800ae#diff-6d186b954a58d5bb740f73d84fe39073R31

Because the options object is also assigned to the eyeglass object, this creates a circular reference. So if you want to walk the options object, you would get an infinite recursion in the form of `eyeglass.options.eyeglass.options.eyeglass.options.eyeglass.options` etc.

Grunt, being the busybody it is, wants to walk the options, resulting in this error message:

> Fatal error: Circular reference detected (.eyeglass.options)

If nothing else, the circular reference should be removed when calling `.sassOptions()`.

**Comment by chriseppstein** [comment]
This circular reference was intentional so that code that is just passed the options will be able to get a reference to eyeglass. I've reworked the code so that the options object returned by `sassOptions()` is not a circular reference to eyeglass.options. That is:

```js
var opts = eyeglass.sassOptions();
opts.eyeglass.options != opts
// => true
opts.eyeglass.options.eyeglass
// => undefined
```
