### ISSUE TITLE
No longer correctly processing subfolders in require statements

### ISSUE THREAD

**Issue by mikl** [sass-eyeglass/eyeglass#54]
This used to work, and works with standard Sass.

In my Sass files, I have a `@import "toolkit/kickstart";` statement, which is supposed to load the file from `node_modules/sass-toolkit/stylesheets/toolkit/_kickstart.scss`.

But Eyeglass seems to strip out the `toolkit/` part when searching for the file, as you can see in the error message:

```
Error: Could not import toolkit/kickstart from any of the following locations: /Users/mikl/Work/Liip/Freitag/vkosf6x3zlyoi/repository/themes/neocortex/sass/partials/global/toolkit/kickstart.scss
sass/partials/global/toolkit/kickstart/index.scss
sass/partials/global/toolkit/kickstart.sass
sass/partials/global/toolkit/kickstart/index.sass
sass/partials/global/toolkit/kickstart.css
sass/partials/global/toolkit/kickstart/index.css
sass/partials/global/toolkit/_kickstart.scss
sass/partials/global/toolkit/kickstart/_index.scss
sass/partials/global/toolkit/_kickstart.sass
sass/partials/global/toolkit/kickstart/_index.sass
sass/partials/global/toolkit/_kickstart.css
sass/partials/global/toolkit/kickstart/_index.css
node_modules/sass-toolkit/stylesheets/kickstart/index.scss
node_modules/sass-toolkit/stylesheets/kickstart.scss
node_modules/sass-toolkit/stylesheets/kickstart/index.sass
node_modules/sass-toolkit/stylesheets/kickstart.sass
node_modules/sass-toolkit/stylesheets/kickstart/index.css
node_modules/sass-toolkit/stylesheets/kickstart.css
node_modules/sass-toolkit/stylesheets/kickstart/_index.scss
node_modules/sass-toolkit/stylesheets/_kickstart.scss
node_modules/sass-toolkit/stylesheets/kickstart/_index.sass
node_modules/sass-toolkit/stylesheets/_kickstart.sass
node_modules/sass-toolkit/stylesheets/kickstart/_index.css
node_modules/sass-toolkit/stylesheets/_kickstart.css
```

If Eyeglass had kept the `toolkit/` part from the import statement, this would work fine.

**Comment by eoneill** [comment]
This looks like it's behaving correctly to me.

Looking at [`sass-toolkit/eyeglass-exports.js`](https://github.com/at-import/toolkit/blob/2.x.x/eyeglass-exports.js), the `sassDir` is `stylesheets/`, so your import in `eyeglass` land would be... `@import "toolkit/toolkit/kickstart"`

Where the first `toolkit/` resolves to the module `sassDir` (`node_modules/sass-toolkit/stylesheets/`) and the second `toolkit/` is relative to that (`node_modules/sass-toolkit/stylesheets/toolkit/`).

When using an `eyeglass` `@import`, the first fragment of the import path is the module name, which resolves to the modules `sassDir` (in this case `stylesheets/`). It's not the same as using `includePaths`.

Did this work in a previous version of `eyeglass`?

For this to work the way you're expecting, I think you'll need to change `sass-toolkit/eyeglass-exports.js` to something like...

```js
module.exports = function(eyeglass, sass) {
  return {
    sassDir: path.join(__dirname, 'stylesheets/toolkit')
  }
}
```
and move the contents of `stylesheets/_toolkit.scss` to `stylesheets/toolkit/_index.scss`

/cc @Snugug

**Comment by mikl** [comment]
Yes, I'm 99% sure this used to work with earlier version of Eyeglass, and completely sure that's how it currently works in ruby-sass.

I understand the rationale, but I think it would still be preferable, if the syntax was the same for ruby-sass as it is with Eyeglass.

**Comment by mikl** [comment]
But in any case, thanks for the feedback :)

**Comment by alanhogan** [comment]
@mikl @eoneill I independently bumped into a similar issue which I categorized as a bug.

Currently (by which I mean before PR #56, so as of 5b217238829f7299eaa6eda73b55efd98342bf6b), the behavior above, with eyeglass modules and imports, is by design, as a perusal through `utils/files.js` will illustrate; the first folder is removed and considered the module name. An `@import` is processed by chopping off the first directory, in many cases. So, `@import "foo/bar/baz"` will sometimes just look for, essentially, `"bar/baz"`.

**Comment by chriseppstein** [comment]
> I think it would still be preferable, if the syntax was the same for ruby-sass as it is with Eyeglass.

I agree. Import statements that work in vanilla ruby-sass or with compass should work in eyeglass.

Please test against 0.6.2. I think it should work now.
