### ISSUE TITLE
Question: Is bundling custom C function out of the scope for eyeglass?

### ISSUE THREAD

**Issue by xzyfer** [sass-eyeglass/eyeglass#6]
> Is bundling custom C function out of the scope for eyeglass?

Pretty self explanatory. Being able to distribute, install and register custom Libsass C functions would be great. It would certainly ease the distribution of custom behaviour without requiring the forking of Libsass (this is a decision I'm currently facing in my team).

**Comment by Jakobo** [comment]
It's well within scope. Given the way gyp files work, it's completely reasonable. If you can `require()`, you should be able to register as a custom function as well. The idea is to being all of the great things about node and npm to the Sass system. :)

**Comment by xzyfer** [comment]
I could hug you. Happy to assist in anyway from the Libsass side of things.

**Comment by chriseppstein** [comment]
Agree. We will probably end up doing something like this for our spriting module. Hugs all around!
