### ISSUE TITLE
Test on Node.js 4

### ISSUE THREAD

**Issue by mzgol** [sass-eyeglass/eyeglass#62]
To test on Node.js 4`.travis.yml` will need:
```yaml
node_js:
  - '0.12'
  - '4'
```

**Comment by chriseppstein** [comment]
Enable and passing now:
https://travis-ci.org/sass-eyeglass/eyeglass/builds/80291527

**Comment by mzgol** [comment]
Perhaps io.js can be removed from Travis then? It's currently commented out.

**Comment by chriseppstein** [comment]
When I enabled io.js the build failed. We'll need to sort out why before that.
