### ISSUE TITLE
Gulp @import is ignored

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#64]
I use the gulp code from docs/integrations/gulp.md.
The top level (non imported) files are parsed and compiled to output css 
but the @imported files are ignored/skipped.

sass.compiler.types.NULL is undefined,
but also when using sass.compiler.types.Null instead won't solve this issue.

Passing true, makes it possible to @import normally - but not the eyeglass modules:
````
done(true);
````

Using node 0.12.7, gulp 3.9.0, eyeglass 0.6.2, gulp-sass 2.0.4 and node-sass 3.2.0.

Thanks
With best regards

**Comment by Etromania** [comment]
Just ran into this as well. Had the fastest compile time ever since my main file is all @imports.

**Comment by pnuzhdin** [comment]
As dirty workaround you could leave done(true) in the fallback importer and add all eyeglass module dependencies of the target eyeglass dependency to your project. Of course it looks weird and may be inconvenient / impossible to do that if you have hundreds of eyeglass dependant modules.

Old eyeglass depends on the deasync version which is not Node 4 compatible. So looks like it's the easiest workaround to use Node 4 and eyeglass with non trivial hierarchy.

**Comment by strarsis** [comment]
With latest sass-eyeglass release it seems to work now, 
for normal @imports and for @importing eyeglass module packages.

I use the following importer now:
````
  importer: function(uri, prev, done) {
      //done(plugins.sass.compiler.types.NULL);
      done(true);
    }
````

Thank you and
With best regards

**Comment by strarsis** [comment]
So this can be closed now as it works with latest eyeglass.
