### ISSUE TITLE
import-once broken when compiling multiple files per eyeglass instance

### ISSUE THREAD

**Issue by hitmands** [sass-eyeglass/eyeglass#65]
Hi,
I've an issue on ***import-once***.

I have two different scss files that will be compiled in two different css files.
In both of these .scss files (for example: bootstrap.scss and application.scss) I need to import a single file called: _variables.scss.

The import-once module seems to prevent this behaviour and in the second file that requires _variables.scss I obtain 
```scss
undefined variable: $variableName
```

is there any workaround for doing this?

Gius

**Comment by chriseppstein** [comment]
are you using gulp?

**Comment by hitmands** [comment]
no, i'm using grunt!

**Comment by hitmands** [comment]
Hi, 
I Think that the problem depends on **ImportUtilities.importOnce**, it seems doesn't pay attemption on the output-file that requests the partial... 

Please, let me know something because i'am using eyeglass on a my project.

**Comment by eoneill** [comment]
I can confirm this issue as well on a metalsmith project. @hitmands, setting `enableImportOnce = false` should unblock you.

```js
var eyeglass = new Eyeglass(...);
eyeglass.enableImportOnce = false;
...
```

I'll look into a proper fix.

**Comment by eoneill** [comment]
@chriseppstein it seems we don't keep track of the top level file, so we don't have any way of keeping track of what was actually imported into the current context.

That is, in [import_utils.js](https://github.com/sass-eyeglass/eyeglass/blob/master/lib/import_utils.js#L51), `this.alreadyImported` is shared across the eyeglass instance (not per file). So import-once (seemingly) only works if a new instance of eyeglass is created per file.

I think this should really be something like... `this.processedFiles[rootFile].alreadyImported`, where `rootFile` is the top most file (the one being compiled).

I did a bit of digging, but I don't think this is currently exposed in the importer. You only seem to have access to the _previous_ file (but not the whole import chain). This might require a patch to node-sass, but I'll keep digging.

**Comment by hitmands** [comment]
@eoneill, thanks, but I can't disable the importOnce prop, 
I need it too :)

By the way, seems a little-fix, so I'll try in the next days!
