### ISSUE TITLE
Use percentages on background positioning

### ISSUE THREAD

**Issue by rachelnabors** [sass-eyeglass/eyeglass#68]
One of compass's inordinately handy features was the ability to set background position values on sprites as percentages, not as pixels. I used the heck out of that in multiple projects, including: http://rachelnabors.com/blackbrickroad/

**Comment by eoneill** [comment]
Thanks for the suggestion. Could you provide an example of how this would be used? Is this more related to [eyeglass-spriting](https://github.com/sass-eyeglass/eyeglass-spriting)?

**Comment by rachelnabors** [comment]
Perhaps it does belong in spriting. So the background positions and sizes as percentages are so very useful when spriting elements that adjust to the size of the viewport, for instance. You need them to resize to fit their scaling container.

**Comment by eoneill** [comment]
Thanks for following up. I'm closing this issue in favor of tracking in eyeglass-spriting.

**Comment by rachelnabors** [comment]
Great! Do I need to submit it in eyeglass-spriting?

**Comment by eoneill** [comment]
I created a ticket in eyeglass-spriting for tracking: https://github.com/sass-eyeglass/eyeglass-spriting/issues/21

**Comment by rachelnabors** [comment]
Awesome, thank you!
