### ISSUE TITLE
node-sass v3.4.0 released, tests fail

### ISSUE THREAD

**Issue by eoneill** [sass-eyeglass/eyeglass#73]
`node-sass` `v3.4.0` was just released. Our test suite currently has several failures against the new version.

**Comment by chriseppstein** [comment]
These are mostly regressions in node-sass and libsass. I'm working with the team to fix them ASAP.

**Comment by eoneill** [comment]
resolved with `node-sass@3.4.2` and `eyeglass@0.6.5`
