### ISSUE TITLE
@import itself for test

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#76]
When a node module should require itself from within its module directory (notably for testing), 
one usually requires it using a relative path:
````
var module = require('../');
````

Is this the same for testing a module from itself?
I tried @import 'file-text'; or @import '../'; but it doesn't work:
````
Uncaught AssertionError: Could not import file-text from stdin
````
or
````
Uncaught AssertionError: Could not import ../ from stdin
````

You can test this by:
````
git clone https://github.com/strarsis/eyeglass-file-text.git
git checkout v0.1.0
nvm use v4.0.0 # for example
npm install
npm test
````
Some other tests may also fail at this time, 
but the @import which is the requirement for testing is failing:
````
Uncaught AssertionError: Could not (import file-text or ../) from stdin
````

Thanks and
with best regards

**Comment by eoneill** [comment]
To do relative imports, you need to pass `file` to the Sass options, in addition to `data`.

```js
new Eyeglass({
  root: rootDir,
  data: input,
  file: ...
}, sass);
```

`file` is the path on disk which `libsass`/`eyeglass` will use to resolve import locations.

Not passing `file` will result in the input being treated as `from stdin`, at which point `libsass` doesn't know where the file is supposed to be on disk and can't resolve relative imports.

**Comment by strarsis** [comment]
Thank you.
With best regards
