### ISSUE TITLE
@import of eyeglass-math (node-sass v3.3.3)

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#77]
I installed eyeglass-math with npm and now try to @import it.
However, it seems to be stuck in a recursive loop 
- but absolute paths are used as downgrade to node-sass v.3.3.3 is forced.

I prepared another git repo to quickly reproduce this issue:
````
git clone https://github.com/strarsis/eyeglass_import_test2.git
cd eyeglass_import_test2

nvm use v4.0.0
npm install

# force using node-sass v3.3.3:
rm -f ./node_modules/gulp-sass/node_modules/.bin/node-sass
rm -f ./node_modules/gulp-sass/node_modules/node-sass/bin/node-sass

gulp sass
````
(Hangs until terminated with Ctrl+c)

I use mostly the Gulpfile from eyeglass documentation (https://github.com/sass-eyeglass/eyeglass/blob/master/docs/integrations/gulp.md) 
plus an importer function which doesn't help though.

Is this an issue with eyeglass-math or eyeglass or with the usage of it (Gulpfile / sass styles)?

Thank you and
With best regards

**Comment by eoneill** [comment]
`gulp-sass` uses `^` for `node-sass` dependency, so it's going to use `3.4.1`.

To workaround this, in your project's `package.json`, lock the version of `node-sass` to `3.3.3`:

```json
"devDependencies": {
  "node-sass": "3.3.3"
}
```
Then in your gulp task, explicitly set that as the compiler for `gulp-sass` to use:

```js
var sass = require("gulp-sass");
sass.compiler = require("node-sass");

...
```

**Comment by strarsis** [comment]
Thank you.
