### ISSUE TITLE
pick static site generator

### ISSUE THREAD

**Issue by xiwcx** [sass-eyeglass/eyeglass#78]
Look at various options and figure what will work best.

## Needs:

- Ability to publish new version along with documentation simultaneously. Website code will live in this repository.
- Ability to use eyeglass in the build (use own dog food)

## Options:

- [http://assemble.io/]()
- [http://harpjs.com/]() (they've offered to allow a PR to include eyeglass as a default)

**Comment by jdsteinbach** [comment]
If we want to fork something & maintain it ourselves, this looks like a reasonably plain Grunt SSG: https://github.com/matthewbdaly/grunt-mini-static-blog

**Comment by xiwcx** [comment]
To be honest I'm confused now about harp.js' offer because their one liner is

> zero-configuration web server with built in pre-processing

From my understandint, even if we can shoehorn eyeglass in there, there wouldn't be a way to add additional plugins?

**Comment by xiwcx** [comment]
throwing this hat in the ring if we decide to go to the custom build route, it's dead simple: https://github.com/segmentio/metalsmith/tree/master/examples/jekyll
