### ISSUE TITLE
Clarification: Nested dependencies

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#82]
What if the eyeglass module "test" uses a different version of eyeglass module "math-eyeglass" 
as dependency than, let's say, eyeglass module "modular-scale"?

The version of the module package is specified in package.json of the respective @importing eyeglass modules package, and they can be well different.

Will an @import yield different SCSS/SASS styles, eyeglass assets and functions 
for each @importing module, isolated from the other eyeglass modules that may use a different version of it?

Or is one version picked for globally for all @importing eyeglass modules, 
regardless of the dependency version in their package.json?

Thank you and
With best regards

**Comment by eoneill** [comment]
Everything is global and the latest version of a requested module is used. That is, eyeglass will dedupe all module references and use the latest version found.

So if your module tree was something like, both `bar` and `foo/bar` will use `v1.1.0`...

```
:root
├── bar@1.0.0
├─┬ foo@...
│ └── bar@1.1.0
└── eyeglass
```

If your module tree looks like this, `bar`, `baz/bar`, and `foo/bar` will all use `v2.0.0`, but you'll get a warning* that they're not semver compatible...
```
:root
├── bar@1.0.0
├─┬ baz@...
│ └── bar@2.0.0
├─┬ foo@...
│ └── bar@1.1.0
└── eyeglass
```

\* Note that I don't think we've actually implemented the warning yet, but it will _eventually_ throw a warning (we already do the check, just don't expose the warning).

**Comment by strarsis** [comment]
So as there is no complex nesting one could partly emulate the eyeglass/sass module loading 
when using node-sass (libsass) without eyeglass by using a custom importer like this one?
https://www.npmjs.com/package/node-sass-custom-importer

**Comment by eoneill** [comment]
You definitely _could_.

Eyeglass is essentially just a custom importer, but it's building an ecosystem and conventions around that importer. `node-sass-custom-importer` is great if that's all you want to do, but you'll lose out on all the other things eyeglass is trying to solve.

**Comment by strarsis** [comment]
How can SCSS/SASS be imported by eyeglass that is not an eyeglass module yet 
(like the eyeglass keyword missing in package info and/or directory structure different)?
Path to ./node_modules/ to the file? Add the node module styles folder to includePath?

Would a "compat"-mode for eyeglass make sense?

With best regards

**Comment by eoneill** [comment]
Yep, adding them to `includePaths` is the preferred approach.

Something like...

```js
var nodeModulesDir = path.join(__dirname, "node_modules");

new Eyeglass({
  ...
  includePaths: [
    path.join(nodeModulesDir, "my-sass-module/path/to/scss"),
    path.join(nodeModulesDir, "foo/sass")
  ]
});
```

We'd also recommend, if possible, submitting a PR to the respective project to enable eyeglass support (usually just requires a few changes to `package.json` and adding `eyeglass-exports.js`) as it will really help propel the community forward.

**Comment by eoneill** [comment]
@strarsis, an you open a new issue for this, as I think it's a different problem.

**Comment by strarsis** [comment]
It appears that include paths passed to sass-eyeglass are relative to the importing file?
Setting root option to main app directory doesn't seem to change that.

With best regards

**Comment by chriseppstein** [comment]
> It appears that include paths passed to sass-eyeglass are relative to the importing file? Setting root option to main app directory doesn't seem to change that.

In node-sass I think relative `includePaths` are implied to be relative to the current working directory. In an eyeglass module I can see how them being relative to the project root might make sense.

**Comment by chriseppstein** [comment]
I filed a new issue to address the relative paths. Closing this as it seems all clarification is done.
