### ISSUE TITLE
Move beyond just wrapping Sass options

### ISSUE THREAD

**Issue by Jakobo** [sass-eyeglass/eyeglass#9]
It appears that most plugins architected on top of `node-sass` use the options object directly. Because eyeglass wants to wrap the options once per render call, this leaves eyeglass incompatible with many node-sass plugins. Instead of changing all of the plugins, this is a proposal to instead wrap node-sass using [cowboy/javascript-hooker](https://github.com/cowboy/javascript-hooker) or a similar library.

----------

Passing `options` through
===
I discovered this issue while exploring what changes we would need to make in [dlmanning/gulp-sass](https://github.com/dlmanning/gulp-sass) in order to support eyeglass. Instead of just an object literal, a function would need to be passed to gulp-sass which returns an options object. This way, during [the map stream transform](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L13), a new option object would be generated each time, ensuring that eyeglass decoration works as expected.

Researching additional node-sass plugins for build systems such as [sindresorhus/grunt-sass](https://github.com/sindresorhus/grunt-sass) and [joliss/broccoli-sass](https://github.com/joliss/broccoli-sass), these too would need to be updated if anything other an an Object literal was going to be passed in to the plugin.

It's my opinion that it is unreasonable to ask every node-sass plugin for a build system to support config decoration.

Alternatives
===
* **making a X-eyeglass which in turn piped through X-sass:** This thin layer of option passing would need to step in during the stream read / per file. We would need to create these per build system. Unfortunately, some build systems such as gulp use object streams which means stitching streams in the plugin which adds to the total amount of maintained code.
* **utilize gulp-tap as a recipe:** Specifically a solution for gulp [geejs/gulp-tap](https://github.com/geejs/gulp-tap) would allow people to use `node-sass` directly in their projects. However, all of the sourcemap support falls apart, a major feature in gulp-sass.
* **update node-sass to support a function for generating options**: The cascade effect of this would be plugin authors updating in order to support this feature universally. However, adding this support be a somewhat significant feature add. I'd like to only ask for this as a last resort.

Proposal
===
Ideally, I'd like eyeglass to work with these sass plugins naturally without any modification to their code, or having to create & maintain separate `X-eyeglass` plugins for build systems. Because the `options` object is passed through directly to node-sass, we should consider addressing instead modifying the `.render()` and `.renderSync()` methods in node-sass.

[cowboy/javascript-hooker](https://github.com/cowboy/javascript-hooker) or a similar library will allow us to cleanly proxy the `render / renderSync` methods, invoking eyeglass once per call. Monkey Patch libraries also come with an API for unhooking, should a developer need to run node-sass without the eyeglass functionality.

This changes our invocation signature from

```js
nodeSass.render(eyeglass({
  /* options */
}));
```

to

```js
require("eyeglass")(nodeSass); // require("eyeglass").bind(nodeSass);
nodeSass.render({
  /* options */
});

require("eyeglass").unbind(nodeSass);
```

I'd really love to collect more thoughts on this, the idea of monkey patching in node.js (completely supported but often only used in testing), and the implications of doing an interface like this.

**Comment by chriseppstein** [comment]
Another option is that we can add some lifecycle callbacks to node-sass directly. Compass and ruby sass both provide lifecycle hooks. Then these callbacks could be passed as options and would live within the same closure to manage local state.

**Comment by Jakobo** [comment]
I think that is a very reasonable idea. Some questions 

* Do we need a post render hook or is the `success()` callback sufficient?
* In addition to the current configuration (by reference), what else does a pre render hook need?
* Are we ok with the eyeglass signature changing to return a function as opposed to the object literal?

Thanks @ch

**Comment by chriseppstein** [comment]
@Jakobo 

Here's the [callbacks that Sass provides](https://github.com/sass/sass/blob/stable/lib/sass/plugin/compiler.rb#L53-L184).

Many of these only make sense for a thing that compiles multiple files. In Sass it's not the core engine that implements these (e.g. libsass's render) but rather it's the wrapper that calls to it, so this would be more like the gulp plugin than the node-sass wrapper.

I'm not sure what you mean by "Are we ok with the eyeglass signature changing to return a function as opposed to the object literal"

**Comment by Jakobo** [comment]
Thanks @chriseppstein, this is really helpful. Since libsass (and thus node-sass (and thus eyeglass)) are designed with single files in mind, we would need a preRender hook. The `updating_stylesheets` is the closest, although it doesn't provide the information that eyeglass would need. Since we actually want to change the options array before rendering, we would be looking for a slightly different hook that the list currently provides.

Regarding the "signature change", currently we use eyeglass as a function that wraps an object literal and returns a new object literal.

```js
nodeSass(eyeglass({
  /* Sass options */
}));
```

Instead, eyeglass would need to return a function (or be the function required) and have a syntax such as `nodeSass({ preRender: eyeglass(), ... })` or `nodeSass({ preRender: eyeglass, ... })`. Either would work, but would change how we've been thinking of eyeglass philosophically as a high-powered option mutator.

**Comment by Jakobo** [comment]
With [node-sass#686](https://github.com/sass/node-sass/pull/686) having landed, I think we can actually preserve the idea of being an option wrapper. Some items we'll want to resolve:

1. We need to know the version of node-sass the they are using at some point. This way, when eyeglass decorates the options, we can avoid backwards incompatible decoration.
2. Transitive dependencies down the import chain are going to be rough. If we have a dependency tree like `A => B => C` and C assumes certain libsass functionality (that A doesn't) then we could end up in an awkward spot. This may just mean we have to modify the `eyeglass-exports.js` to include semver information for node-sass and libsass

I'm going to close this for now, and we can open a ticket once we better understand the dependency challenges.
