### ISSUE TITLE
Deprecate redundant capabilities

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#93]
This is a general planning issue for simplifying our API for the 1.0 release. I'll make new issues for things that we decide here.

# `sassDir`

Currently, we allow `sassDir` to be specified in `package.json` as well as in `eyeglass-exports.js`.

The `package.json` approach is much more user friendly. However, the `eyeglass-exports.js` approach
allows the module to inspect the eyeglass options before deciding on the Sass directory. There is
some interesting things this enables, like letting people opt into a new version of a module's
stylesheets by setting some option. But this is unlikely to be useful very often and there's
probably a simpler way to accomplish that use case.

# `eyeglass-exports.js` location

Currently you can specify the eyeglass-exports file three ways in `package.json`:
`pkg.main`, `pkg.eyeglass`, and `pkg.eyeglass.exports`. Given that we basically require a
`pkg.eyeglass.needs` attribute at the very least, the `pkg.eyeglass` seems useless.

I think the `pkg.main` form has some usefulness for pure eyeglass modules.

# revisit `require('eyeglass')` exports

This currently exports a class and a decorator function.

```js
// class function
var Eyeglass = require('eyeglass').Eyeglass;
// decorator function
var eyeglass = require('eyeglass').decorate;
```

We can collapse this into
a single function that behaves differently depending on whether it is called with `new`.

```js
// returns an eyeglass instance
var Eyeglass = require('eyeglass');
var eyeglass = new Eyeglass({});
// returns options
var eyeglass = require('eyeglass');
var sassOptions = eyeglass({});
```

I'm not sure I'm a fan of this approach. Alternatively we can leave decorate as a function
attached to the exported function. 

```js
// returns an eyeglass instance
var Eyeglass = require('eyeglass');
var eyeglass = new Eyeglass({});
// returns options
var sassOptions = Eyeglass.decorate({});
```

# What else?

If there are other redundant configuration or APIs, please mention them.

**Comment by eoneill** [comment]
## `sassDir`

I think there's value in both. `sassDir` in `package.json` significantly reduces the barrier to entry, but supporting `sassDir` via the export model gives much more flexibility. I say keep both, but we should throw an error is both or neither sources set `sassDir`

## `eyeglass-exports.js` location

The initial reasoning for falling back to `main` was that it would make the adoption easier. I think `sassDir` in `package.json` is a better solution and avoids confusion. I say...

One of `eyeglass.exports` or `eyeglass.sassDir` is required.

If `eyeglass.exports` is specified, we always `require()` it. If `eyeglass.sassDir` is specified, the export should not set `sassDir`.

Never fallback to `main`. If we think it's valuable, we can support something like `{"eyeglass": {"exports": "PKG_MAIN"}}`, but I'd prefer not to.

## revisit `require('eyeglass')` exports

I was already working on this today and basically did what you just said. See #94

## What else?

### public methods

We expose a lot of methods on `Eyeglass.prototype`. I don't like it :)

Most of these methods seem like they are unneccesary and do not need to be exposed on the public API. See #94 for a list of these methods.

### sassOptions vs eyeglassOptions

We should segregate the two to avoid collisions. We should be explicit that `sassOptions` are documented on the `node-sass` site and we should support all those by passing them through and only touch what we need to. `eyeglassOptions` are the options that modify eyeglass behavior (`root`, `enableImportOnce`, etc). See also #94

**Comment by scottdavis** [comment]
So just some documentation questions when calling decorate you are decorating the sassOptions to be passed into node-sass?

**Comment by eoneill** [comment]
@scottdavis, yep with the current implementation, `eyeglass.decorate(options)` "decorates" the options for node-sass. Similarly, `(new Eyeglass(options)).sassOptions()` will return the decorated options. And currently the options passed in contain node-sass and eyeglass options.

With separating the respective options, the proposal would look something like:

```js
var options = eyeglass(
  // sassOptions @see https://github.com/sass/node-sass#options
  {
    file: "foo.scss",
    includePaths: ["some/path"],
    outputStyle: "expanded",
    ...
  },
  // eyeglassOptions
  {
    root: __dirname,
    buildDir: path.join(__dirname, "dist"),
    cacheDir: path.join(__dirname, ".cache"),
    enableImportOnce: false,
    engines: {
      sass: require("node-sass") // use a specific node-sass version
    },
    ...
  }
);
```

In the simplest use case (no eyeglass configuration needed), this would look something like:

```js
var options = eyeglass({
  file: "foo.scss"
});

sass.render(options, ...);
```

**Comment by eoneill** [comment]
other ideas...

## expand `needs` support

Currently, `{"eyeglass": {"needs": "^0.7.1"}}` will specify the version of eyeglass that you claim compatibility with. I think we should also expand this to include `node-sass` and `libsass` checking:

```json
{
  "eyeglass": {
    "needs": {
      "eyeglass": "^0.7.1",
      "node-sass": ">=3.4.2"
    }
  }
}
```

Given that `libsass` and `node-sass` versions are coupled, we might not need to (or want to) support `libsass` in this context.

## `"eyeglass"` must be an object

Currently, you can do this...

```json
{
  "eyeglass": "./export-eyeglass.js"
}
```

Since we are _strongly_ recommending the `needs` property, consider deprecating this and requiring the more explicit:

```json
{
  "eyeglass": {
    "exports": "./export-eyeglass.js"
  }
}
```

**Comment by chriseppstein** [comment]
We did a good job on these. I'm closing this. We can track other refactorings individually.
