### ISSUE TITLE
Explicit modules

### ISSUE THREAD

**Issue by davidkpiano** [sass-eyeglass/eyeglass#96]
Hey @chriseppstein  -

In writing [Sassport](https://github.com/davidkpiano/sassport), probably the biggest difference between that project and Eyeglass was the ability to explicitly include modules, which is modeled after what PostCSS does (in terms of including modules). 

The external API of Eyeglass is quite a bit different than Sassport in that Eyeglass is _passed in_ as options in Sass whereas Sassport _wraps_ Sass, but we can still make this work:

```js
var sass = require('node-sass');
var eyeglass = require('eyeglass'); // pending https://github.com/sass-eyeglass/eyeglass/pull/94

// Local modules - part of project, no need/desire to include them via NPM
var fooModule = require('./path/to/foo-eyeglass-module');
var barModule = require('./path/to/bar-eyeglass-module');

var eyeglassOptions = eyeglass(sassOptions, eyeglassOptions)
  .modules([ fooModule, barModule ]);

sass(eyeglassOptions).render(...);
```

Then these modules can be imported in any Sass file just like any other Eyeglass module, via `@import 'foo'`, etc. I think this would be a great additional feature because:

1. it bypasses potentially unnecessary searching through `node_modules`,
2. it allows the module to come from anywhere, whether it's NPM, bower, in-project, etc. etc.
3. No need to add anything extra to a module's `package.json` file
4. NPM isn't really for assets, such as fonts or images. This makes using Eyeglass as it currently is a little out-of-place for assets. 

Would you consider explicit modules?

**Comment by eoneill** [comment]
@scottdavis had a similar ask to do something like this.

I think there's value in it, but we make a lot of assumptions with the current module discovery.

Thinking about this last night, I think the API would look something like...

```js
var Eyeglass = require("eyeglass");
var eyeglass = new Eyeglass(...);

eyeglass.modules.add(function(eyeglass, sass) {
  return {
    name: "my-module",
    functions: { ... },
    assets: [],
    sassDir: ...
  };
});
```
There are intricacies to consider here. I'll reply with a follow up (probably on Monday) with some concerns and how we might handle them.

**Comment by davidkpiano** [comment]
Not the biggest fan of the imperative syntax that implies only one module can be added at a time, though. But yeah, that would be great if it were considered.

**Comment by eoneill** [comment]
`#modules.add` could take an array. I'm more interested in what is actually be passed to it (e.g. a function) and what that entails.

Currently, most of the module information is derived from `package.json`. If we allow registering arbitrary modules, we cannot rely on package.json. So we'd have to decide what the module export looks like in that case.

It also complicates things as there are now two ways to build an eyeglass module.

I'm still not a huge fan of this, but I can see the value.

**Comment by chriseppstein** [comment]
@davidkpiano, I don't understand why the `includePaths` option isn't enough for these other modules.

**Comment by eoneill** [comment]
`includePaths` is fine if you have a pure sass module. `includePaths` won't work if you use any of eyeglass' more useful functionality, like exposing assets or javascript functions.

**Comment by chriseppstein** [comment]
@eoneill If you are using any of eyeglass's more useful functionality, you can have a package.json and an exports file. I don't understand what use case we're trying to support.

**Comment by eoneill** [comment]
We don't parse `package.json` from anything in `includePaths`. So with the current system, the only way to consume an eyeglass module is declare it as an npm dependency.

**Comment by chriseppstein** [comment]
@eoneill I'm not super excited about making eyeglass a general purpose module loader for every way of distributing code ever conceived. NPM has features for distributing private modules now. Bower is basically dead. If the code is in project, the user can simply pass in the `functions` to eyeglass as a node-sass option and they can put the sass code on the include path and in-project assets are already supported.

**Comment by chriseppstein** [comment]
@davidkpiano 

> it bypasses potentially unnecessary searching through node_modules

Eyeglass would still have to search through node_modules even if there were explicit modules defined. AFAIK, this isn't a huge perf hit.

> it allows the module to come from anywhere, whether it's NPM, bower, in-project, etc. etc.

As I've said, supporting other module distribution systems isn't something I want in eyeglass 1.0. I want to keep our focus on the primary use case.

> No need to add anything extra to a module's package.json file.

I don't understand why adding some stuff to package.json is bad. Please explain when and why this fails.

> NPM isn't really for assets, such as fonts or images. This makes using Eyeglass as it currently is a little out-of-place for assets.

What about the eyeglass asset system is "out-of-place"?

**Comment by davidkpiano** [comment]
@chriseppstein Fair points. I'm just trying to envision the possible use-cases where NPM wouldn't be appropriate - it seems a little restrictive, especially given that assets are not one of the main use-cases for NPM (and shouldn't be - for public packages - if the assets are meant to be private).

**Comment by chriseppstein** [comment]
@davidkpiano I prefer to think of it as "focused" instead of "restrictive" :) Also, I'm not sure I share your philosophy on assets. I see them as a kind of public API and a lot of eyeglass is built around the concept that assets should be explicitly declared by a module and manageable as part of the public API (Anything you can make a URL to is public). maybe we're talking about different kinds of assets?

**Comment by davidkpiano** [comment]
We might be - I'm thinking about non-CSS assets, such as fonts or images. Things that wouldn't typically be sourced from NPM.

**Comment by chriseppstein** [comment]
@davidkpiano why wouldn't those things be sourced from npm? how would you share a theme that uses background images and fonts without distributing the corresponding assets as a single module?

**Comment by davidkpiano** [comment]
Personally, our team uses Pixelapse (basically, like Github for designers). I suppose it makes sense if you have an all-NPM workflow, though, to restrict modules to NPM.

**Comment by chriseppstein** [comment]
@davidkpiano So you distribute a theme via npm and that theme has references to assets that the theme doesn't distribute? I don't want to support an arrangement like that -- it seems contrary to best practices.

**Comment by davidkpiano** [comment]
In general, it would be a good idea to poll the community and see how they are distributing their themes, and what the ideal workflow would be for them. It may be NPM, it may not be. My personal opinion is that forcing a single way of distribution is not a good idea.

**Comment by chriseppstein** [comment]
> It may be NPM, it may not be. My personal opinion is that forcing a single way of distribution is not a good idea.

I'm not forcing anything. Eyeglass is a plugin system for npm. If you're using npm, eyeglass is a good choice, if you're not, it's probably not. This project is opinionated in that sense. It's core to the value of the ecosystem. If eyeglass plugins can be distributed through many mechanisms then there's no central way for plugins to depend on each other. This is one of those situations where being opinionated works out better than being flexible.
