### ISSUE TITLE
import once: evaluate vs render

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#97]
I use eyeglass + gulp and enabled import once.
I declare @imports in each file explicitly, separately.

This worked with compass import once and it works with plain node-sass and import-once importer -
but with eyeglass import once, variables, mixins and other internal/evaluatable things (scope) 
aren't apparently available in files using subsequent @imports.

E.g. when @importing './base/_palette' in several files,
the variables/maps/etc aren't available in those files (after the first one probably).

When I set eyeglass.enableImportOnce back to false to disable import once, 
it works again, the variables are available again and everything compiles.

Is this now because the importOnce got issues with project-relative paths (starting with './') 
or because it really skips those @imports and constrains the scope to the first import occurrence?

I am preparing a trimmed down example for this issue.

Thank you and
With best regards

**Comment by eoneill** [comment]
There is no scope in sass, so I doubt that's the issue.

The way import-once in eyeglass works is, if the file has already been imported, the custom importer returns an empty string.

You can try enabling debugging and see if it reveals anything:
```sh
$ DEBUG=eyeglass:import gulp sass
```

Let me know when you have an example to reproduce and I'll take a look.

**Comment by strarsis** [comment]
Thank you for your answer.

Finally figured out what happens:
I use gulp.src(...) with a folder that contains partial files (filename starting with underscore (_)) 
and two normal files (filename not starting with underscore), print.scss and styles.scss.

style.scss and print.scss _both_ @imports _palette.scss.
But both are isolated, they don't @import each other, hence their scopes are indeed isolated.

import once feature of eyeglass reports to me (thanks to your debug tip) that _palette.scss 
has been already @imported by print.scss - hence styles.scss will not re-@import it - 
and the variables are missing in styles.scss and all other files @imported by it.

So the import once feature needs to build a @import tree from each top level style file individually.

Thank you and
With best regards

**Comment by strarsis** [comment]
I will open a new issue for this.
